/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedChar91__flags__Char93RouteImport } from './routes/_authenticated/[__flags__]'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedJoinRouteImport } from './routes/_authenticated/join'
import { Route as AuthenticatedInterviewsShareCodeRouteImport } from './routes/_authenticated/interviews/$shareCode'
import { Route as AuthenticatedInterviewsNewRouteImport } from './routes/_authenticated/interviews/new'
import { Route as AuthenticatedRecruiterInterviewsRouteImport } from './routes/_authenticated/recruiter/interviews'
import { Route as AuthenticatedInterviewsShareCodeIndexRouteImport } from './routes/_authenticated/interviews/$shareCode/index'
import { Route as AuthenticatedInterviewsOwnedInterviewIdRouteImport } from './routes/_authenticated/interviews/owned.$interviewId'
import { Route as AuthenticatedInterviewsShareCodeAttemptsAttemptIdRouteImport } from './routes/_authenticated/interviews/$shareCode/attempts/$attemptId'
import { Route as AuthenticatedInterviewsOwnedInterviewIdEditRouteImport } from './routes/_authenticated/interviews/owned.$interviewId_.edit'
import { Route as AuthenticatedInterviewsOwnedInterviewIdParticipantsRouteImport } from './routes/_authenticated/interviews/owned.$interviewId_.participants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChar91__flags__Char93Route =
  AuthenticatedChar91__flags__Char93RouteImport.update({
    id: '/__flags__',
    path: '/__flags__',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJoinRoute = AuthenticatedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInterviewsShareCodeRoute =
  AuthenticatedInterviewsShareCodeRouteImport.update({
    id: '/interviews/$shareCode',
    path: '/interviews/$shareCode',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewsNewRoute =
  AuthenticatedInterviewsNewRouteImport.update({
    id: '/interviews/new',
    path: '/interviews/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecruiterInterviewsRoute =
  AuthenticatedRecruiterInterviewsRouteImport.update({
    id: '/recruiter/interviews',
    path: '/recruiter/interviews',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewsShareCodeIndexRoute =
  AuthenticatedInterviewsShareCodeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInterviewsShareCodeRoute,
  } as any)
const AuthenticatedInterviewsOwnedInterviewIdRoute =
  AuthenticatedInterviewsOwnedInterviewIdRouteImport.update({
    id: '/interviews/owned/$interviewId',
    path: '/interviews/owned/$interviewId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute =
  AuthenticatedInterviewsShareCodeAttemptsAttemptIdRouteImport.update({
    id: '/attempts/$attemptId',
    path: '/attempts/$attemptId',
    getParentRoute: () => AuthenticatedInterviewsShareCodeRoute,
  } as any)
const AuthenticatedInterviewsOwnedInterviewIdEditRoute =
  AuthenticatedInterviewsOwnedInterviewIdEditRouteImport.update({
    id: '/interviews/owned/$interviewId_/edit',
    path: '/interviews/owned/$interviewId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewsOwnedInterviewIdParticipantsRoute =
  AuthenticatedInterviewsOwnedInterviewIdParticipantsRouteImport.update({
    id: '/interviews/owned/$interviewId_/participants',
    path: '/interviews/owned/$interviewId/participants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/__flags__': typeof AuthenticatedChar91__flags__Char93Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/join': typeof AuthenticatedJoinRoute
  '/interviews/$shareCode': typeof AuthenticatedInterviewsShareCodeRouteWithChildren
  '/interviews/new': typeof AuthenticatedInterviewsNewRoute
  '/recruiter/interviews': typeof AuthenticatedRecruiterInterviewsRoute
  '/interviews/owned/$interviewId': typeof AuthenticatedInterviewsOwnedInterviewIdRoute
  '/interviews/$shareCode/': typeof AuthenticatedInterviewsShareCodeIndexRoute
  '/interviews/$shareCode/attempts/$attemptId': typeof AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute
  '/interviews/owned/$interviewId/edit': typeof AuthenticatedInterviewsOwnedInterviewIdEditRoute
  '/interviews/owned/$interviewId/participants': typeof AuthenticatedInterviewsOwnedInterviewIdParticipantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/__flags__': typeof AuthenticatedChar91__flags__Char93Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/join': typeof AuthenticatedJoinRoute
  '/interviews/new': typeof AuthenticatedInterviewsNewRoute
  '/recruiter/interviews': typeof AuthenticatedRecruiterInterviewsRoute
  '/interviews/owned/$interviewId': typeof AuthenticatedInterviewsOwnedInterviewIdRoute
  '/interviews/$shareCode': typeof AuthenticatedInterviewsShareCodeIndexRoute
  '/interviews/$shareCode/attempts/$attemptId': typeof AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute
  '/interviews/owned/$interviewId/edit': typeof AuthenticatedInterviewsOwnedInterviewIdEditRoute
  '/interviews/owned/$interviewId/participants': typeof AuthenticatedInterviewsOwnedInterviewIdParticipantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/__flags__': typeof AuthenticatedChar91__flags__Char93Route
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/join': typeof AuthenticatedJoinRoute
  '/_authenticated/interviews/$shareCode': typeof AuthenticatedInterviewsShareCodeRouteWithChildren
  '/_authenticated/interviews/new': typeof AuthenticatedInterviewsNewRoute
  '/_authenticated/recruiter/interviews': typeof AuthenticatedRecruiterInterviewsRoute
  '/_authenticated/interviews/owned/$interviewId': typeof AuthenticatedInterviewsOwnedInterviewIdRoute
  '/_authenticated/interviews/$shareCode/': typeof AuthenticatedInterviewsShareCodeIndexRoute
  '/_authenticated/interviews/$shareCode/attempts/$attemptId': typeof AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute
  '/_authenticated/interviews/owned/$interviewId_/edit': typeof AuthenticatedInterviewsOwnedInterviewIdEditRoute
  '/_authenticated/interviews/owned/$interviewId_/participants': typeof AuthenticatedInterviewsOwnedInterviewIdParticipantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/__flags__'
    | '/dashboard'
    | '/join'
    | '/interviews/$shareCode'
    | '/interviews/new'
    | '/recruiter/interviews'
    | '/interviews/owned/$interviewId'
    | '/interviews/$shareCode/'
    | '/interviews/$shareCode/attempts/$attemptId'
    | '/interviews/owned/$interviewId/edit'
    | '/interviews/owned/$interviewId/participants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/__flags__'
    | '/dashboard'
    | '/join'
    | '/interviews/new'
    | '/recruiter/interviews'
    | '/interviews/owned/$interviewId'
    | '/interviews/$shareCode'
    | '/interviews/$shareCode/attempts/$attemptId'
    | '/interviews/owned/$interviewId/edit'
    | '/interviews/owned/$interviewId/participants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/__flags__'
    | '/_authenticated/dashboard'
    | '/_authenticated/join'
    | '/_authenticated/interviews/$shareCode'
    | '/_authenticated/interviews/new'
    | '/_authenticated/recruiter/interviews'
    | '/_authenticated/interviews/owned/$interviewId'
    | '/_authenticated/interviews/$shareCode/'
    | '/_authenticated/interviews/$shareCode/attempts/$attemptId'
    | '/_authenticated/interviews/owned/$interviewId_/edit'
    | '/_authenticated/interviews/owned/$interviewId_/participants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/__flags__': {
      id: '/_authenticated/__flags__'
      path: '/__flags__'
      fullPath: '/__flags__'
      preLoaderRoute: typeof AuthenticatedChar91__flags__Char93RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/join': {
      id: '/_authenticated/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthenticatedJoinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interviews/$shareCode': {
      id: '/_authenticated/interviews/$shareCode'
      path: '/interviews/$shareCode'
      fullPath: '/interviews/$shareCode'
      preLoaderRoute: typeof AuthenticatedInterviewsShareCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interviews/new': {
      id: '/_authenticated/interviews/new'
      path: '/interviews/new'
      fullPath: '/interviews/new'
      preLoaderRoute: typeof AuthenticatedInterviewsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recruiter/interviews': {
      id: '/_authenticated/recruiter/interviews'
      path: '/recruiter/interviews'
      fullPath: '/recruiter/interviews'
      preLoaderRoute: typeof AuthenticatedRecruiterInterviewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interviews/$shareCode/': {
      id: '/_authenticated/interviews/$shareCode/'
      path: '/'
      fullPath: '/interviews/$shareCode/'
      preLoaderRoute: typeof AuthenticatedInterviewsShareCodeIndexRouteImport
      parentRoute: typeof AuthenticatedInterviewsShareCodeRoute
    }
    '/_authenticated/interviews/owned/$interviewId': {
      id: '/_authenticated/interviews/owned/$interviewId'
      path: '/interviews/owned/$interviewId'
      fullPath: '/interviews/owned/$interviewId'
      preLoaderRoute: typeof AuthenticatedInterviewsOwnedInterviewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interviews/$shareCode/attempts/$attemptId': {
      id: '/_authenticated/interviews/$shareCode/attempts/$attemptId'
      path: '/attempts/$attemptId'
      fullPath: '/interviews/$shareCode/attempts/$attemptId'
      preLoaderRoute: typeof AuthenticatedInterviewsShareCodeAttemptsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedInterviewsShareCodeRoute
    }
    '/_authenticated/interviews/owned/$interviewId_/edit': {
      id: '/_authenticated/interviews/owned/$interviewId_/edit'
      path: '/interviews/owned/$interviewId/edit'
      fullPath: '/interviews/owned/$interviewId/edit'
      preLoaderRoute: typeof AuthenticatedInterviewsOwnedInterviewIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interviews/owned/$interviewId_/participants': {
      id: '/_authenticated/interviews/owned/$interviewId_/participants'
      path: '/interviews/owned/$interviewId/participants'
      fullPath: '/interviews/owned/$interviewId/participants'
      preLoaderRoute: typeof AuthenticatedInterviewsOwnedInterviewIdParticipantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedInterviewsShareCodeRouteChildren {
  AuthenticatedInterviewsShareCodeIndexRoute: typeof AuthenticatedInterviewsShareCodeIndexRoute
  AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute: typeof AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute
}

const AuthenticatedInterviewsShareCodeRouteChildren: AuthenticatedInterviewsShareCodeRouteChildren =
  {
    AuthenticatedInterviewsShareCodeIndexRoute:
      AuthenticatedInterviewsShareCodeIndexRoute,
    AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute:
      AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute,
  }

const AuthenticatedInterviewsShareCodeRouteWithChildren =
  AuthenticatedInterviewsShareCodeRoute._addFileChildren(
    AuthenticatedInterviewsShareCodeRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedChar91__flags__Char93Route: typeof AuthenticatedChar91__flags__Char93Route
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJoinRoute: typeof AuthenticatedJoinRoute
  AuthenticatedInterviewsShareCodeRoute: typeof AuthenticatedInterviewsShareCodeRouteWithChildren
  AuthenticatedInterviewsNewRoute: typeof AuthenticatedInterviewsNewRoute
  AuthenticatedRecruiterInterviewsRoute: typeof AuthenticatedRecruiterInterviewsRoute
  AuthenticatedInterviewsOwnedInterviewIdRoute: typeof AuthenticatedInterviewsOwnedInterviewIdRoute
  AuthenticatedInterviewsOwnedInterviewIdEditRoute: typeof AuthenticatedInterviewsOwnedInterviewIdEditRoute
  AuthenticatedInterviewsOwnedInterviewIdParticipantsRoute: typeof AuthenticatedInterviewsOwnedInterviewIdParticipantsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChar91__flags__Char93Route:
    AuthenticatedChar91__flags__Char93Route,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJoinRoute: AuthenticatedJoinRoute,
  AuthenticatedInterviewsShareCodeRoute:
    AuthenticatedInterviewsShareCodeRouteWithChildren,
  AuthenticatedInterviewsNewRoute: AuthenticatedInterviewsNewRoute,
  AuthenticatedRecruiterInterviewsRoute: AuthenticatedRecruiterInterviewsRoute,
  AuthenticatedInterviewsOwnedInterviewIdRoute:
    AuthenticatedInterviewsOwnedInterviewIdRoute,
  AuthenticatedInterviewsOwnedInterviewIdEditRoute:
    AuthenticatedInterviewsOwnedInterviewIdEditRoute,
  AuthenticatedInterviewsOwnedInterviewIdParticipantsRoute:
    AuthenticatedInterviewsOwnedInterviewIdParticipantsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
