/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInterviewsShareCodeRouteImport } from './routes/_authenticated/interviews/$shareCode'
import { Route as AuthenticatedInterviewsNewRouteImport } from './routes/_authenticated/interviews/new'
import { Route as AuthenticatedInterviewsShareCodeIndexRouteImport } from './routes/_authenticated/interviews/$shareCode/index'
import { Route as AuthenticatedInterviewsOwnedInterviewIdRouteImport } from './routes/_authenticated/interviews/owned.$interviewId'
import { Route as AuthenticatedInterviewsShareCodeAttemptsAttemptIdRouteImport } from './routes/_authenticated/interviews/$shareCode/attempts/$attemptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInterviewsShareCodeRoute =
  AuthenticatedInterviewsShareCodeRouteImport.update({
    id: '/interviews/$shareCode',
    path: '/interviews/$shareCode',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewsNewRoute =
  AuthenticatedInterviewsNewRouteImport.update({
    id: '/interviews/new',
    path: '/interviews/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewsShareCodeIndexRoute =
  AuthenticatedInterviewsShareCodeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInterviewsShareCodeRoute,
  } as any)
const AuthenticatedInterviewsOwnedInterviewIdRoute =
  AuthenticatedInterviewsOwnedInterviewIdRouteImport.update({
    id: '/interviews/owned/$interviewId',
    path: '/interviews/owned/$interviewId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute =
  AuthenticatedInterviewsShareCodeAttemptsAttemptIdRouteImport.update({
    id: '/attempts/$attemptId',
    path: '/attempts/$attemptId',
    getParentRoute: () => AuthenticatedInterviewsShareCodeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interviews/$shareCode': typeof AuthenticatedInterviewsShareCodeRouteWithChildren
  '/interviews/new': typeof AuthenticatedInterviewsNewRoute
  '/interviews/owned/$interviewId': typeof AuthenticatedInterviewsOwnedInterviewIdRoute
  '/interviews/$shareCode/': typeof AuthenticatedInterviewsShareCodeIndexRoute
  '/interviews/$shareCode/attempts/$attemptId': typeof AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interviews/new': typeof AuthenticatedInterviewsNewRoute
  '/interviews/owned/$interviewId': typeof AuthenticatedInterviewsOwnedInterviewIdRoute
  '/interviews/$shareCode': typeof AuthenticatedInterviewsShareCodeIndexRoute
  '/interviews/$shareCode/attempts/$attemptId': typeof AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/interviews/$shareCode': typeof AuthenticatedInterviewsShareCodeRouteWithChildren
  '/_authenticated/interviews/new': typeof AuthenticatedInterviewsNewRoute
  '/_authenticated/interviews/owned/$interviewId': typeof AuthenticatedInterviewsOwnedInterviewIdRoute
  '/_authenticated/interviews/$shareCode/': typeof AuthenticatedInterviewsShareCodeIndexRoute
  '/_authenticated/interviews/$shareCode/attempts/$attemptId': typeof AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/interviews/$shareCode'
    | '/interviews/new'
    | '/interviews/owned/$interviewId'
    | '/interviews/$shareCode/'
    | '/interviews/$shareCode/attempts/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/interviews/new'
    | '/interviews/owned/$interviewId'
    | '/interviews/$shareCode'
    | '/interviews/$shareCode/attempts/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/interviews/$shareCode'
    | '/_authenticated/interviews/new'
    | '/_authenticated/interviews/owned/$interviewId'
    | '/_authenticated/interviews/$shareCode/'
    | '/_authenticated/interviews/$shareCode/attempts/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interviews/$shareCode': {
      id: '/_authenticated/interviews/$shareCode'
      path: '/interviews/$shareCode'
      fullPath: '/interviews/$shareCode'
      preLoaderRoute: typeof AuthenticatedInterviewsShareCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interviews/new': {
      id: '/_authenticated/interviews/new'
      path: '/interviews/new'
      fullPath: '/interviews/new'
      preLoaderRoute: typeof AuthenticatedInterviewsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interviews/$shareCode/': {
      id: '/_authenticated/interviews/$shareCode/'
      path: '/'
      fullPath: '/interviews/$shareCode/'
      preLoaderRoute: typeof AuthenticatedInterviewsShareCodeIndexRouteImport
      parentRoute: typeof AuthenticatedInterviewsShareCodeRoute
    }
    '/_authenticated/interviews/owned/$interviewId': {
      id: '/_authenticated/interviews/owned/$interviewId'
      path: '/interviews/owned/$interviewId'
      fullPath: '/interviews/owned/$interviewId'
      preLoaderRoute: typeof AuthenticatedInterviewsOwnedInterviewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interviews/$shareCode/attempts/$attemptId': {
      id: '/_authenticated/interviews/$shareCode/attempts/$attemptId'
      path: '/attempts/$attemptId'
      fullPath: '/interviews/$shareCode/attempts/$attemptId'
      preLoaderRoute: typeof AuthenticatedInterviewsShareCodeAttemptsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedInterviewsShareCodeRoute
    }
  }
}

interface AuthenticatedInterviewsShareCodeRouteChildren {
  AuthenticatedInterviewsShareCodeIndexRoute: typeof AuthenticatedInterviewsShareCodeIndexRoute
  AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute: typeof AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute
}

const AuthenticatedInterviewsShareCodeRouteChildren: AuthenticatedInterviewsShareCodeRouteChildren =
  {
    AuthenticatedInterviewsShareCodeIndexRoute:
      AuthenticatedInterviewsShareCodeIndexRoute,
    AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute:
      AuthenticatedInterviewsShareCodeAttemptsAttemptIdRoute,
  }

const AuthenticatedInterviewsShareCodeRouteWithChildren =
  AuthenticatedInterviewsShareCodeRoute._addFileChildren(
    AuthenticatedInterviewsShareCodeRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInterviewsShareCodeRoute: typeof AuthenticatedInterviewsShareCodeRouteWithChildren
  AuthenticatedInterviewsNewRoute: typeof AuthenticatedInterviewsNewRoute
  AuthenticatedInterviewsOwnedInterviewIdRoute: typeof AuthenticatedInterviewsOwnedInterviewIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInterviewsShareCodeRoute:
    AuthenticatedInterviewsShareCodeRouteWithChildren,
  AuthenticatedInterviewsNewRoute: AuthenticatedInterviewsNewRoute,
  AuthenticatedInterviewsOwnedInterviewIdRoute:
    AuthenticatedInterviewsOwnedInterviewIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
